export const CITY_API_LOADING = "CITY_API_LOADING";
export const CITY_API_SUCCESS = "CITY_API_SUCCESS";
export const CITY_API_ERROR = "CITY_API_ERROR";
export const CITY_API_DELETE = "CITY_API_DELETE";
export const OLD_CITY_API_SUCCESS = "OLD_CITY_API_SUCCESS";
