export const CITY_API_LOADING = "CITY_API_LOADING";
export const CITY_API_SUCCESS = "CITY_API_SUCCESS";
export const CITY_API_ERROR = "CITY_API_ERROR";
export const CITY_API_DELETE = "CITY_API_DELETE";
export const OLD_CITY_API_SUCCESS = "OLD_CITY_API_SUCCESS";

export const WEATHER_API_SUCCESS = "WEATHER_API_SUCCESS";
export const WEATHER_API_ERROR = "WEATHER_API_ERROR";
export const WEATHER_API_DELETE = "WEATHER_API_DELETE";

export const SET_TEMP_UNIT="SET_TEMP_UNIT";

export const TODAYS_HIGHLIGHT="TODAYS_HIGHLIGHT";